# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21968d420dad4c1ea0daede025dce9cbda3b80043858d54fb243a93c55a3ff354f4bdff7dbe5adc136a035e5d1985cf1cf103b46d3c0276626d3d9ce79357404

test:
  secret_key_base: 991823b957fdd25a856e962bd4ea6904895722e0894caa635e5060be8b7320e9b40e8ce3734818cd12412b2bdb37ce85d5b68b22f9a8c8d8732bcc9b5f00a7a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
